import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Must come last — disables any ESLint formatting rules that would
  // otherwise conflict with Prettier, which owns formatting exclusively.
  prettierConfig,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Purchased WordPress theme kept as a visual reference only — never
    // linted, never imported as code.
    "florial/**",
    // Generated Prisma client output.
    "src/generated/**",
    // Auto-generated by scripts/generate-migrations-data.ts — long
    // embedded SQL string literals, not hand-written code to lint.
    "src/server/db/migrations-data.ts",
  ]),
]);

export default eslintConfig;
