/**
 * Regenerates src/server/db/migrations-data.ts by reading every
 * prisma/migrations/<name>/migration.sql file and embedding its contents
 * as plain TypeScript string literals.
 *
 * Why this exists: Hostinger's actual runtime environment (as opposed to
 * the build environment) turned out not to include the `prisma/` source
 * directory at all — only `.next` and a pruned `node_modules` survive,
 * confirmed by a boot-time "prisma/migrations not found" error even after
 * migrate.ts's fs.readdirSync/readFileSync approach worked perfectly in
 * every local test. Next.js's own build-time file tracer only ships files
 * actually reached via `import`/`require`/`fs` calls it can statically
 * see — a runtime `fs.readFileSync` on a path built from `process.cwd()`
 * isn't something it can trace, so the raw .sql files silently never made
 * the trip. Embedding them as real imported TS source sidesteps that
 * entirely — the tracer sees an ordinary `import`, same as every other
 * module in this app that's already proven to survive deployment.
 *
 * Run manually (`npx tsx scripts/generate-migrations-data.ts`) any time a
 * new migration is added — this repo doesn't wire it into postinstall/
 * prebuild on purpose: the generated file is committed to git precisely
 * so nothing about deploying depends on this script having run correctly
 * in whatever environment does the deploying.
 */
import fs from "node:fs";
import path from "node:path";

const migrationsDir = path.join(process.cwd(), "prisma", "migrations");
const outputPath = path.join(process.cwd(), "src", "server", "db", "migrations-data.ts");

const names = fs
  .readdirSync(migrationsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const entries = names
  .map((name) => {
    const sqlPath = path.join(migrationsDir, name, "migration.sql");
    if (!fs.existsSync(sqlPath)) return null;
    const sql = fs.readFileSync(sqlPath, "utf-8");
    return `  { name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`;
  })
  .filter((entry): entry is string => entry !== null);

const output = `// AUTO-GENERATED by scripts/generate-migrations-data.ts — do not hand-edit.
// Regenerate after adding/changing a migration:
//   npx tsx scripts/generate-migrations-data.ts
//
// Embeds every prisma/migrations/<name>/migration.sql as a string literal
// so server/db/migrate.ts's boot-time migration runner doesn't need
// filesystem access to prisma/migrations/ at runtime — see that
// generator's own doc comment for why (Hostinger's runtime doesn't ship
// that directory).

export interface MigrationEntry {
  name: string;
  sql: string;
}

export const MIGRATIONS: MigrationEntry[] = [
${entries.join("\n")}
];
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote ${names.length} migrations to ${outputPath}`);
